# Generated by Django 6.0.2 on 2026-02-07 06:14

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('proof_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('link', 'Link'), ('document', 'Document')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('trust_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('vote_count', models.IntegerField(default=0)),
                ('is_mature', models.BooleanField(default=False)),
                ('is_classified', models.BooleanField(default=False)),
                ('final_classification', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProofVote',
            fields=[
                ('proof_vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('SUPPORTS', 'Supports'), ('UNCERTAIN', 'Uncertain'), ('REFUTES', 'Refutes')], max_length=10)),
                ('vote_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('weight_snapshot', models.DecimalField(decimal_places=4, max_digits=6)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rumor',
            fields=[
                ('rumor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(500)])),
                ('trust_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('vote_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('proof_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('momentum_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, choices=[('VERIFIED_TRUE', 'Verified True'), ('LIKELY_TRUE', 'Likely True'), ('UNCERTAIN', 'Uncertain'), ('LIKELY_FALSE', 'Likely False'), ('VERIFIED_FALSE', 'Verified False')], max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_type', models.CharField(blank=True, choices=[('photo', 'Photo'), ('link', 'Link'), ('document', 'Document')], max_length=20, null=True)),
                ('evidence_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('VERIFY', 'Verify'), ('UNCERTAIN', 'Uncertain'), ('DISPUTE', 'Dispute')], max_length=10)),
                ('vote_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('weight_snapshot', models.DecimalField(decimal_places=4, max_digits=6)),
                ('voter_reputation_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('change_count', models.IntegerField(default=0)),
            ],
        ),
    ]
