# Generated by Django 6.0.2 on 2026-02-07 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rumors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofvote',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rumors.proof'),
        ),
        migrations.AddField(
            model_name='proofvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rumor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_rumors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proof',
            name='rumor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='rumors.rumor'),
        ),
        migrations.AddField(
            model_name='vote',
            name='rumor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rumors.rumor'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='proofvote',
            unique_together={('proof', 'voter')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('rumor', 'voter')},
        ),
    ]
