# Generated by Django 6.0.2 on 2026-02-07 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('rumor_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('calculation_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CORRECT_VOTE', 'Correct Vote'), ('INCORRECT_VOTE', 'Incorrect Vote'), ('HELPFUL_PROOF', 'Helpful Proof'), ('MISLEADING_PROOF', 'Misleading Proof'), ('AUTHOR_BONUS', 'Author Bonus'), ('AUTHOR_PENALTY', 'Author Penalty')], max_length=30)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rumor_id', models.UUIDField(blank=True, null=True)),
                ('proof_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
